package com.job_manager.mai.contrains;

public enum Permission {
    MANAGE_JOB_READ,
    MANAGE_JOB_CREATE,
    MANAGE_JOB_UPDATE,
    MANAGE_JOB_DELETE,

    MANAGE_KPI_READ,
    MANAGE_KPI_CREATE,
    MANAGE_KPI_UPDATE,
    MANAGE_KPI_DELETE,

    MANAGE_USER_READ,
    MANAGE_USER_CREATE,
    MANAGE_USER_UPDATE,
    MANAGE_USER_DELETE,

    MANAGE_PERMISSION_READ,
    MANAGE_PERMISSION_CREATE,
    MANAGE_PERMISSION_UPDATE,
    MANAGE_PERMISSION_DELETE,

    MANAGE_ROLE_READ,

    MANAGE_ROLE_CREATE,
    MANAGE_ROLE_UPDATE,
    MANAGE_ROLE_DELETE,

    MANAGE_PLAN_READ,
    MANAGE_PLAN_CREATE,
    MANAGE_PLAN_UPDATE,
    MANAGE_PLAN_DELETE,

    MANAGE_ACCOUNT_READ,
    MANAGE_ACCOUNT_CREATE,
    MANAGE_ACCOUNT_UPDATE,
    MANAGE_ACCOUNT_DELETE,

}
